### ISSUE TITLE
Priority Operator Error

### ISSUE THREAD

**Issue by JohnCoates** [robb/Cartography#241]
The priority example in the Readme fails to compile on Swift 3.0

````
var constraint: NSLayoutConstraint!
constrain(view) { (view: LayoutProxy) in
    constraint = view.width == 200 ~ 100
}            
expect(constraint.priority).to(equal(100))
````

Errors:

````
Cartography/CartographyTests/PrioritySpec.swift:22:28: error: adjacent operators are in unordered precedence groups 'AssignmentPrecedence' and 'CarthographyPriorityPrecedence'
                constraint = view.width == 200 ~ 100
                           ^                   ~
Cartography/CartographyTests/PrioritySpec.swift:22:48: error: binary operator '~' cannot be applied to operands of type '()' and 'Int'
                constraint = view.width == 200 ~ 100
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~
Cartography/CartographyTests/PrioritySpec.swift:22:48: note: overloads for '~' exist with these partially matching parameter lists: (NSLayoutConstraint, LayoutPriority), ([NSLayoutConstraint], LayoutPriority)
                constraint = view.width == 200 ~ 100
````

**Comment by orta** [comment]
Yeah, the implicit `LayoutPriority` was something we couldn't figure out when [porting to Swift 3](https://github.com/robb/Cartography/pull/228#issuecomment-244346734) - I'd love for you to dig in here and see if you can figure that one out?

**Comment by JohnCoates** [comment]
Okay, sure I'll have a go at it

**Comment by JohnCoates** [comment]
I've filed a [Swift bug report](https://bugs.swift.org/browse/SR-2823) and a [radar](https://openradar.appspot.com/radar?id=4943067677196288) about this issue. The more radars that get filed, the more traction the bug gets, so I recommend filing one also.

**Comment by orta** [comment]
Perfect! Shipped as 1.0.1 - thanks!
